"""add_is_temporary_to_rooms

Revision ID: ca418b87b3d7
Revises: f35a8c645f28
Create Date: 2026-01-19 02:18:20.438910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca418b87b3d7'
down_revision = 'f35a8c645f28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_temporary', sa.Boolean(), nullable=False, server_default='false', comment='是否为临时房间（点对点通话）'))
    op.create_index(op.f('ix_rooms_is_temporary'), 'rooms', ['is_temporary'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_is_temporary'), table_name='rooms')
    op.drop_column('rooms', 'is_temporary')
    # ### end Alembic commands ###
