"""add_note_field_to_friendships

Revision ID: f35a8c645f28
Revises: fb0533610cf1
Create Date: 2026-01-12 05:11:41.857651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35a8c645f28'
down_revision = 'fb0533610cf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('note', sa.String(length=200), nullable=True, comment='备注（用户对好友的备注名称）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendships', 'note')
    # ### end Alembic commands ###
