"""Add language field to users table for i18n support

Revision ID: 9aafef0fbc55
Revises: 368a9ade7d37
Create Date: 2026-01-09 23:50:37.200743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aafef0fbc55'
down_revision = '368a9ade7d37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(length=10), nullable=False, comment='用户语言偏好（如：zh_CN, en_US）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
