"""add_is_admin_field_to_users_table

Revision ID: 36dfee9c7d1c
Revises: 9aafef0fbc55
Create Date: 2026-01-10 00:46:09.558945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dfee9c7d1c'
down_revision = '9aafef0fbc55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, comment='是否为管理员账户'))
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
