"""add_rooms_and_room_participants_tables

Revision ID: f07fd654883e
Revises: 985535698c99
Create Date: 2026-01-10 01:54:13.159324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07fd654883e'
down_revision = '985535698c99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=100), nullable=False, comment='房间ID（唯一）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者用户ID'),
    sa.Column('room_name', sa.String(length=200), nullable=True, comment='房间名称'),
    sa.Column('max_occupants', sa.Integer(), nullable=False, comment='最大在线人数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_room_active', 'rooms', ['is_active'], unique=False)
    op.create_index('idx_room_created_by', 'rooms', ['created_by'], unique=False)
    op.create_index('idx_room_id', 'rooms', ['room_id'], unique=False)
    op.create_index(op.f('ix_rooms_created_by'), 'rooms', ['created_by'], unique=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_is_active'), 'rooms', ['is_active'], unique=False)
    op.create_index(op.f('ix_rooms_room_id'), 'rooms', ['room_id'], unique=True)
    op.create_table('room_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('is_moderator', sa.Boolean(), nullable=False, comment='是否为主持人'),
    sa.Column('joined_at', sa.DateTime(), nullable=False, comment='加入时间'),
    sa.Column('left_at', sa.DateTime(), nullable=True, comment='离开时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否在线'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_room_user')
    )
    op.create_index('idx_participant_active', 'room_participants', ['is_active'], unique=False)
    op.create_index('idx_participant_room', 'room_participants', ['room_id'], unique=False)
    op.create_index('idx_participant_user', 'room_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_room_participants_id'), 'room_participants', ['id'], unique=False)
    op.create_index(op.f('ix_room_participants_is_active'), 'room_participants', ['is_active'], unique=False)
    op.create_index(op.f('ix_room_participants_room_id'), 'room_participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_participants_user_id'), 'room_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_participants_user_id'), table_name='room_participants')
    op.drop_index(op.f('ix_room_participants_room_id'), table_name='room_participants')
    op.drop_index(op.f('ix_room_participants_is_active'), table_name='room_participants')
    op.drop_index(op.f('ix_room_participants_id'), table_name='room_participants')
    op.drop_index('idx_participant_user', table_name='room_participants')
    op.drop_index('idx_participant_room', table_name='room_participants')
    op.drop_index('idx_participant_active', table_name='room_participants')
    op.drop_table('room_participants')
    op.drop_index(op.f('ix_rooms_room_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_is_active'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_created_by'), table_name='rooms')
    op.drop_index('idx_room_id', table_name='rooms')
    op.drop_index('idx_room_created_by', table_name='rooms')
    op.drop_index('idx_room_active', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
