"""add_file_fields_to_messages

Revision ID: 6b47a5052638
Revises: ca418b87b3d7
Create Date: 2026-01-23 06:52:19.186797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b47a5052638'
down_revision = 'ca418b87b3d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_type', sa.String(length=20), nullable=False, comment='通话类型：video/audio'),
    sa.Column('call_status', sa.String(length=20), nullable=False, comment='通话状态：initiated/ringing/connected/ended/rejected/missed'),
    sa.Column('caller_id', sa.Integer(), nullable=False, comment='发起者用户ID'),
    sa.Column('callee_id', sa.Integer(), nullable=True, comment='接收者用户ID（点对点通话）'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='房间ID（房间通话）'),
    sa.Column('jitsi_room_id', sa.String(length=100), nullable=False, comment='Jitsi房间ID（用于加入Jitsi会议）'),
    sa.Column('start_time', sa.DateTime(), nullable=True, comment='通话开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='通话结束时间'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='通话时长（秒）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间（发起时间）'),
    sa.ForeignKeyConstraint(['callee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='通话记录表'
    )
    op.create_index(op.f('ix_calls_call_status'), 'calls', ['call_status'], unique=False)
    op.create_index(op.f('ix_calls_call_type'), 'calls', ['call_type'], unique=False)
    op.create_index(op.f('ix_calls_callee_id'), 'calls', ['callee_id'], unique=False)
    op.create_index(op.f('ix_calls_caller_id'), 'calls', ['caller_id'], unique=False)
    op.create_index(op.f('ix_calls_created_at'), 'calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.create_index(op.f('ix_calls_jitsi_room_id'), 'calls', ['jitsi_room_id'], unique=False)
    op.create_index(op.f('ix_calls_room_id'), 'calls', ['room_id'], unique=False)
    op.add_column('messages', sa.Column('file_id', sa.Integer(), nullable=True, comment='文件ID（关联files表）'))
    op.add_column('messages', sa.Column('file_url', sa.String(length=500), nullable=True, comment='文件访问URL（服务器转储或HTTP上传的文件）'))
    op.add_column('messages', sa.Column('file_name', sa.String(length=255), nullable=True, comment='文件名'))
    op.add_column('messages', sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'))
    op.create_index(op.f('ix_messages_file_id'), 'messages', ['file_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'files', ['file_id'], ['id'], ondelete='SET NULL')
    op.alter_column('rooms', 'is_temporary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='是否为临时房间（点对点通话）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'is_temporary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='是否为临时房间（点对点通话）',
               existing_nullable=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_file_id'), table_name='messages')
    op.drop_column('messages', 'file_size')
    op.drop_column('messages', 'file_name')
    op.drop_column('messages', 'file_url')
    op.drop_column('messages', 'file_id')
    op.drop_index(op.f('ix_calls_room_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_jitsi_room_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_created_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_caller_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_callee_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_type'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_status'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
