"""add_messages_table_for_chat

Revision ID: 39e1ba3aaa98
Revises: 49f2d339a98e
Create Date: 2026-01-12 02:20:44.010164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39e1ba3aaa98'
down_revision = '49f2d339a98e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='发送者用户ID'),
    sa.Column('receiver_id', sa.Integer(), nullable=True, comment='接收者用户ID（点对点消息）'),
    sa.Column('room_id', sa.Integer(), nullable=True, comment='房间ID（房间群聊消息）'),
    sa.Column('message', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment='消息类型：text/image/file/audio/system'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='已读时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='发送时间'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='聊天消息表'
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.alter_column('operation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_comment='操作时间',
               existing_nullable=False)
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.alter_column('qrcode_scans', 'encrypted_data',
               existing_type=sa.TEXT(),
               comment='加密的二维码数据（加密或未加密）',
               existing_comment='加密的二维码数据',
               existing_nullable=False)
    op.alter_column('qrcode_scans', 'qrcode_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='二维码类型：encrypted（加密）或 plain（未加密）',
               existing_nullable=False)
    op.create_foreign_key(None, 'room_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('rooms', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='创建者用户ID')
    op.create_index(op.f('ix_rooms_created_by'), 'rooms', ['created_by'], unique=False)
    op.create_foreign_key(None, 'rooms', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('system_configs_config_key_key', 'system_configs', type_='unique')
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table_comment(
        'system_configs',
        '系统配置表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_comment='用户语言偏好',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='用户角色：super_admin/room_owner/user',
               existing_nullable=True)
    op.alter_column('users', 'default_max_occupants',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='房主房间默认最大人数上限',
               existing_nullable=True)
    op.alter_column('users', 'is_disabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='是否禁用',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_disabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='是否禁用',
               existing_nullable=True)
    op.alter_column('users', 'default_max_occupants',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_comment='房主房间默认最大人数上限',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'::character varying"),
               existing_comment='用户角色：super_admin/room_owner/user',
               existing_nullable=True)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'zh_TW'::character varying"),
               existing_comment='用户语言偏好',
               existing_nullable=True)
    op.drop_table_comment(
        'system_configs',
        existing_comment='系统配置表',
        schema=None
    )
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.create_unique_constraint('system_configs_config_key_key', 'system_configs', ['config_key'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_created_by'), table_name='rooms')
    op.alter_column('rooms', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='创建者用户ID')
    op.drop_constraint(None, 'room_participants', type_='foreignkey')
    op.alter_column('qrcode_scans', 'qrcode_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'encrypted'::character varying"),
               existing_comment='二维码类型：encrypted（加密）或 plain（未加密）',
               existing_nullable=False)
    op.alter_column('qrcode_scans', 'encrypted_data',
               existing_type=sa.TEXT(),
               comment='加密的二维码数据',
               existing_comment='加密的二维码数据（加密或未加密）',
               existing_nullable=False)
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.alter_column('operation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_comment='操作时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
