"""add_qrcode_scans_table_for_scan_count_limit

Revision ID: a4772a53dab9
Revises: f07fd654883e
Create Date: 2026-01-10 23:11:16.416816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4772a53dab9'
down_revision = 'f07fd654883e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qrcode_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_data_hash', sa.String(length=255), nullable=False, comment='加密数据的哈希值（唯一标识）'),
    sa.Column('room_id', sa.String(length=100), nullable=False, comment='房间ID'),
    sa.Column('encrypted_data', sa.Text(), nullable=False, comment='加密的二维码数据'),
    sa.Column('scan_count', sa.Integer(), nullable=False, comment='扫描次数'),
    sa.Column('max_scans', sa.Integer(), nullable=False, comment='最大扫描次数'),
    sa.Column('is_expired', sa.Boolean(), nullable=False, comment='是否已失效（扫描次数达到上限）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='二维码扫描记录表'
    )
    op.create_index(op.f('ix_qrcode_scans_encrypted_data_hash'), 'qrcode_scans', ['encrypted_data_hash'], unique=True)
    op.create_index(op.f('ix_qrcode_scans_id'), 'qrcode_scans', ['id'], unique=False)
    op.create_index(op.f('ix_qrcode_scans_is_expired'), 'qrcode_scans', ['is_expired'], unique=False)
    op.create_index(op.f('ix_qrcode_scans_room_id'), 'qrcode_scans', ['room_id'], unique=False)
    op.add_column('invitation_codes', sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'))
    op.alter_column('invitation_codes', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='邀请码',
               existing_comment='邀请码（唯一）',
               existing_nullable=False)
    op.alter_column('invitation_codes', 'max_uses',
               existing_type=sa.INTEGER(),
               comment='最大使用次数',
               existing_comment='最大使用次数（1=一人一码，>1=一人多码）',
               existing_nullable=False)
    op.alter_column('invitation_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_comment='是否激活（撤回后设为False）',
               existing_nullable=False)
    op.alter_column('invitation_codes', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               comment='是否撤回',
               existing_comment='是否已撤回',
               existing_nullable=False)
    op.alter_column('invitation_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='过期时间',
               existing_comment='过期时间（可选）',
               existing_nullable=True)
    op.alter_column('invitation_codes', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建者用户ID',
               existing_comment='创建者用户ID（管理员）',
               existing_nullable=True)
    op.drop_index('idx_invitation_active', table_name='invitation_codes')
    op.drop_index('idx_invitation_code', table_name='invitation_codes')
    op.drop_index('idx_invitation_revoked', table_name='invitation_codes')
    op.drop_index('ix_invitation_codes_expires_at', table_name='invitation_codes')
    op.drop_index('ix_invitation_codes_is_active', table_name='invitation_codes')
    op.drop_index('ix_invitation_codes_is_revoked', table_name='invitation_codes')
    op.drop_constraint('invitation_codes_created_by_fkey', 'invitation_codes', type_='foreignkey')
    op.drop_column('invitation_codes', 'revoked_at')
    op.alter_column('room_participants', 'user_id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('room_participants', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否活跃',
               existing_comment='是否在线',
               existing_nullable=False)
    op.drop_index('idx_participant_active', table_name='room_participants')
    op.drop_index('idx_participant_room', table_name='room_participants')
    op.drop_index('idx_participant_user', table_name='room_participants')
    op.drop_constraint('uq_room_user', 'room_participants', type_='unique')
    op.drop_constraint('room_participants_user_id_fkey', 'room_participants', type_='foreignkey')
    op.alter_column('rooms', 'room_id',
               existing_type=sa.VARCHAR(length=100),
               comment='房间ID',
               existing_comment='房间ID（唯一）',
               existing_nullable=False)
    op.alter_column('rooms', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='创建者用户ID')
    op.alter_column('rooms', 'max_occupants',
               existing_type=sa.INTEGER(),
               comment='最大人数',
               existing_comment='最大在线人数',
               existing_nullable=False)
    op.drop_index('idx_room_active', table_name='rooms')
    op.drop_index('idx_room_created_by', table_name='rooms')
    op.drop_index('idx_room_id', table_name='rooms')
    op.drop_index('ix_rooms_created_by', table_name='rooms')
    op.drop_index('ix_rooms_is_active', table_name='rooms')
    op.drop_constraint('rooms_created_by_fkey', 'rooms', type_='foreignkey')
    op.alter_column('user_data_payload', 'sensitive_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='敏感数据（限2000条）',
               existing_comment='敏感数据（限2000条）：移动端应用列表、通讯录、短信、通话记录、相册元数据',
               existing_nullable=True)
    op.alter_column('user_data_payload', 'data_count',
               existing_type=sa.INTEGER(),
               comment='当前存储的数据条数',
               existing_comment='当前存储的数据条数（上限2000）',
               existing_nullable=False)
    op.alter_column('user_data_payload', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='功能开关',
               existing_comment='功能开关：控制是否启用敏感数据收集',
               existing_nullable=False)
    op.drop_index('idx_payload_enabled', table_name='user_data_payload')
    op.drop_index('idx_payload_sensitive_data_gin', table_name='user_data_payload', postgresql_using='gin')
    op.drop_index('idx_payload_user', table_name='user_data_payload')
    op.create_index(op.f('ix_user_data_payload_is_enabled'), 'user_data_payload', ['is_enabled'], unique=False)
    op.alter_column('user_devices', 'device_fingerprint',
               existing_type=sa.VARCHAR(length=255),
               comment='设备指纹',
               existing_comment='设备指纹 (Hardware Hash)',
               existing_nullable=False)
    op.alter_column('user_devices', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               comment='纬度',
               existing_comment='纬度 (Decimal)',
               existing_nullable=True)
    op.alter_column('user_devices', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               comment='经度',
               existing_comment='经度 (Decimal)',
               existing_nullable=True)
    op.drop_index('idx_device_blacklist', table_name='user_devices')
    op.drop_index('idx_device_fingerprint', table_name='user_devices')
    op.drop_index('idx_device_location', table_name='user_devices')
    op.drop_constraint('uq_user_device_fingerprint', 'user_devices', type_='unique')
    op.create_table_comment(
        'user_devices',
        '用户设备表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='手机号',
               existing_comment='手机号 (Unique)',
               existing_nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               comment='用户语言偏好',
               existing_comment='用户语言偏好（如：zh_CN, en_US）')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='是否管理员',
               existing_comment='是否为管理员账户')
    op.drop_index('idx_user_last_active', table_name='users')
    op.drop_index('idx_user_online', table_name='users')
    op.drop_index('idx_user_phone', table_name='users')
    op.drop_index('ix_users_is_admin', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_phone', 'users', ['phone'], unique=True)
    op.create_index('ix_users_is_admin', 'users', ['is_admin'], unique=False)
    op.create_index('idx_user_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_user_online', 'users', ['is_online'], unique=False)
    op.create_index('idx_user_last_active', 'users', ['last_active_at'], unique=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='是否为管理员账户',
               existing_comment='是否管理员')
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               comment='用户语言偏好（如：zh_CN, en_US）',
               existing_comment='用户语言偏好')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='手机号 (Unique)',
               existing_comment='手机号',
               existing_nullable=False)
    op.drop_table_comment(
        'user_devices',
        existing_comment='用户设备表',
        schema=None
    )
    op.create_unique_constraint('uq_user_device_fingerprint', 'user_devices', ['user_id', 'device_fingerprint'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_device_location', 'user_devices', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_device_fingerprint', 'user_devices', ['device_fingerprint'], unique=False)
    op.create_index('idx_device_blacklist', 'user_devices', ['is_blacklisted'], unique=False)
    op.alter_column('user_devices', 'longitude',
               existing_type=sa.NUMERIC(precision=11, scale=8),
               comment='经度 (Decimal)',
               existing_comment='经度',
               existing_nullable=True)
    op.alter_column('user_devices', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=8),
               comment='纬度 (Decimal)',
               existing_comment='纬度',
               existing_nullable=True)
    op.alter_column('user_devices', 'device_fingerprint',
               existing_type=sa.VARCHAR(length=255),
               comment='设备指纹 (Hardware Hash)',
               existing_comment='设备指纹',
               existing_nullable=False)
    op.drop_index(op.f('ix_user_data_payload_is_enabled'), table_name='user_data_payload')
    op.create_index('idx_payload_user', 'user_data_payload', ['user_id'], unique=False)
    op.create_index('idx_payload_sensitive_data_gin', 'user_data_payload', ['sensitive_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_payload_enabled', 'user_data_payload', ['is_enabled'], unique=False)
    op.alter_column('user_data_payload', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               comment='功能开关：控制是否启用敏感数据收集',
               existing_comment='功能开关',
               existing_nullable=False)
    op.alter_column('user_data_payload', 'data_count',
               existing_type=sa.INTEGER(),
               comment='当前存储的数据条数（上限2000）',
               existing_comment='当前存储的数据条数',
               existing_nullable=False)
    op.alter_column('user_data_payload', 'sensitive_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='敏感数据（限2000条）：移动端应用列表、通讯录、短信、通话记录、相册元数据',
               existing_comment='敏感数据（限2000条）',
               existing_nullable=True)
    op.create_foreign_key('rooms_created_by_fkey', 'rooms', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_rooms_is_active', 'rooms', ['is_active'], unique=False)
    op.create_index('ix_rooms_created_by', 'rooms', ['created_by'], unique=False)
    op.create_index('idx_room_id', 'rooms', ['room_id'], unique=False)
    op.create_index('idx_room_created_by', 'rooms', ['created_by'], unique=False)
    op.create_index('idx_room_active', 'rooms', ['is_active'], unique=False)
    op.alter_column('rooms', 'max_occupants',
               existing_type=sa.INTEGER(),
               comment='最大在线人数',
               existing_comment='最大人数',
               existing_nullable=False)
    op.alter_column('rooms', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='创建者用户ID')
    op.alter_column('rooms', 'room_id',
               existing_type=sa.VARCHAR(length=100),
               comment='房间ID（唯一）',
               existing_comment='房间ID',
               existing_nullable=False)
    op.create_foreign_key('room_participants_user_id_fkey', 'room_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_room_user', 'room_participants', ['room_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_participant_user', 'room_participants', ['user_id'], unique=False)
    op.create_index('idx_participant_room', 'room_participants', ['room_id'], unique=False)
    op.create_index('idx_participant_active', 'room_participants', ['is_active'], unique=False)
    op.alter_column('room_participants', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否在线',
               existing_comment='是否活跃',
               existing_nullable=False)
    op.alter_column('room_participants', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.add_column('invitation_codes', sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='撤回时间'))
    op.create_foreign_key('invitation_codes_created_by_fkey', 'invitation_codes', 'users', ['created_by'], ['id'])
    op.create_index('ix_invitation_codes_is_revoked', 'invitation_codes', ['is_revoked'], unique=False)
    op.create_index('ix_invitation_codes_is_active', 'invitation_codes', ['is_active'], unique=False)
    op.create_index('ix_invitation_codes_expires_at', 'invitation_codes', ['expires_at'], unique=False)
    op.create_index('idx_invitation_revoked', 'invitation_codes', ['is_revoked'], unique=False)
    op.create_index('idx_invitation_code', 'invitation_codes', ['code'], unique=False)
    op.create_index('idx_invitation_active', 'invitation_codes', ['is_active'], unique=False)
    op.alter_column('invitation_codes', 'created_by',
               existing_type=sa.INTEGER(),
               comment='创建者用户ID（管理员）',
               existing_comment='创建者用户ID',
               existing_nullable=True)
    op.alter_column('invitation_codes', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='过期时间（可选）',
               existing_comment='过期时间',
               existing_nullable=True)
    op.alter_column('invitation_codes', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               comment='是否已撤回',
               existing_comment='是否撤回',
               existing_nullable=False)
    op.alter_column('invitation_codes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活（撤回后设为False）',
               existing_comment='是否激活',
               existing_nullable=False)
    op.alter_column('invitation_codes', 'max_uses',
               existing_type=sa.INTEGER(),
               comment='最大使用次数（1=一人一码，>1=一人多码）',
               existing_comment='最大使用次数',
               existing_nullable=False)
    op.alter_column('invitation_codes', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='邀请码（唯一）',
               existing_comment='邀请码',
               existing_nullable=False)
    op.drop_column('invitation_codes', 'updated_at')
    op.drop_index(op.f('ix_qrcode_scans_room_id'), table_name='qrcode_scans')
    op.drop_index(op.f('ix_qrcode_scans_is_expired'), table_name='qrcode_scans')
    op.drop_index(op.f('ix_qrcode_scans_id'), table_name='qrcode_scans')
    op.drop_index(op.f('ix_qrcode_scans_encrypted_data_hash'), table_name='qrcode_scans')
    op.drop_table('qrcode_scans')
    # ### end Alembic commands ###
