"""add_invitation_codes_table

Revision ID: 985535698c99
Revises: 36dfee9c7d1c
Create Date: 2026-01-10 01:01:01.016716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985535698c99'
down_revision = '36dfee9c7d1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment='邀请码（唯一）'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者用户ID（管理员）'),
    sa.Column('max_uses', sa.Integer(), nullable=False, comment='最大使用次数（1=一人一码，>1=一人多码）'),
    sa.Column('used_count', sa.Integer(), nullable=False, comment='已使用次数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活（撤回后设为False）'),
    sa.Column('is_revoked', sa.Boolean(), nullable=False, comment='是否已撤回'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('revoked_at', sa.DateTime(), nullable=True, comment='撤回时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间（可选）'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invitation_active', 'invitation_codes', ['is_active'], unique=False)
    op.create_index('idx_invitation_code', 'invitation_codes', ['code'], unique=False)
    op.create_index('idx_invitation_revoked', 'invitation_codes', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_invitation_codes_code'), 'invitation_codes', ['code'], unique=True)
    op.create_index(op.f('ix_invitation_codes_expires_at'), 'invitation_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invitation_codes_id'), 'invitation_codes', ['id'], unique=False)
    op.create_index(op.f('ix_invitation_codes_is_active'), 'invitation_codes', ['is_active'], unique=False)
    op.create_index(op.f('ix_invitation_codes_is_revoked'), 'invitation_codes', ['is_revoked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_codes_is_revoked'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_is_active'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_id'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_expires_at'), table_name='invitation_codes')
    op.drop_index(op.f('ix_invitation_codes_code'), table_name='invitation_codes')
    op.drop_index('idx_invitation_revoked', table_name='invitation_codes')
    op.drop_index('idx_invitation_code', table_name='invitation_codes')
    op.drop_index('idx_invitation_active', table_name='invitation_codes')
    op.drop_table('invitation_codes')
    # ### end Alembic commands ###
