#!/usr/bin/env bash
# 清理冗余说明文档，保留根目录 README.md 为唯一主文档
# 在项目根目录执行：bash scripts/cleanup_redundant_docs.sh

set -e
cd "$(dirname "$0")/.."

clean_root() {
  rm -f .env.backup cursorrules.txt
  rm -f ANDROID_BUILD_NEXT_STEPS.md ANDROID_BUILD_PROGRESS.md API_COMPLETION_SUMMARY.md APK_BUILD_SUMMARY.md APK_DOWNLOAD_LINKS.md
  rm -f ARCHITECTURE_ANALYSIS.md BUILD_STATUS_SUMMARY.txt BUILD_STATUS.md CHAT_FEATURE_ANALYSIS.md CLEANUP_LOGS_AND_EXTERNAL_LINKS.md
  rm -f COMPLETE_TEST_CHECKLIST.md DASHBOARD_LAYOUT_FINAL.md DATA_LIMITS_CONFIGURATION.md DEPLOYMENT_CHECKLIST.md DEPLOYMENT_GUIDE_v0112-0930.md
  rm -f DEPLOYMENT_QUICK_START.md DEPLOYMENT_READY.md DEPLOYMENT_TEST_RESULTS.md docker-mirror-setup.md DOMAIN_CONFIG.md
  rm -f FAVICON_TEST_RESULTS.md FLUTTER_IOS_DEVELOPMENT_OPTIONS.md HEX8_ROOM_ID_ANALYSIS.md
  rm -f I18N_FRONTEND_UPDATE.md I18N_IMPLEMENTATION.md I18N_STATUS.md I18N_UPDATE_SUMMARY.md
  rm -f JITSI_CUSTOMIZATION.md JITSI_DEPLOYMENT.md JITSI_ROOM_LIFECYCLE_DISCUSSION.md JITSI_SELF_HOSTED_DOMAIN_CONFIG.md JITSI_SETUP.md
  rm -f JOIN_ROOM_GUIDE.md LANGUAGE_MIGRATION_PROGRESS.md LAYOUT_REQUIREMENTS.md LAYOUT_GRID_SPEC.md
  rm -f LOG_CHAT_DOMAIN_SETUP.md LOG_CHAT_DOMAIN_SUMMARY.md MOBILE_PRIVACY_IMPLEMENTATION_SUMMARY.md MOBILE_PRIVACY_PERMISSIONS_DISCUSSION.md MOBILE_DEV_SETUP.md
  rm -f OFFLINE_DEPLOYMENT.md PROGRESS_2026_01_11.md PROGRESS_2026_01_24_DEVICE_MANAGEMENT.md PROGRESS_IMAGE_FEATURE.md PROGRESS_NOTES.md
  rm -f PROGRESS_PERMISSIONS.md PROGRESS_SUMMARY_20260112.md PROGRESS_VIDEO_CALL_NEXT.md PROJECT_SUMMARY.md
  rm -f QRCODE_CHAT_ENTRY_FIX.md QRCODE_DENSITY_PREVIEW.md QRCODE_OPTIMIZATION.md QRCODE_SECURITY.md QRCODE_VERSION10_ANALYSIS.md QRCODE_ISSUE_DIAGNOSIS.md QRCODE_DATA_STRUCTURE.md
  rm -f QUICK_START.md README_API_TEST.md README_I18N_DEMO.md README_OFFLINE.md ROOM_ID_FORMAT.md
  rm -f SERVER_RESTART_NOTICE.md SERVER_RUNNING.md SERVER_STATUS.md SOCKETIO_DOMAIN_ANALYSIS.md SOCKETIO_FEATURES_COMPLETE.md
  rm -f SSL_CERTIFICATE_SETUP.md TEST_CHAT_FEATURE.md TEST_CLEANUP_SUMMARY.md TEST_RESULTS.md TEST_STATUS.md TESTING_AND_DEPLOYMENT.md TEST_LOG_CHAT_RESULTS.md TEST_ACCOUNTS.md
  rm -f VERSIONS.md WEBRTC_FIX.md WECHAT_LEVEL_QRCODE_ANALYSIS.md 完整测试流程.md 测试说明.md
  rm -f APP_VS_WEB_CHAT_COMPARISON.md DEVICE_MANAGEMENT_PLAN.md CHAT_ACCESS_GUIDE.md CHAT_IMPLEMENTATION_SUMMARY.md
  rm -f DEPLOYMENT_STATUS.md DEPLOYMENT_TEST_COMPLETE.md ACCESS_URLS.md BROWSER_ACCESS.md FAVICON_TEST_PROGRESS.md ICON_SETUP_COMPLETE.md
  rm -f HEX8_ROOM_ID_IMPLEMENTATION.md API_PROGRESS.md API_ALIGNMENT_FIXES.md WORK_SESSION_SUMMARY_2026_01_11.md JITSI_HTTPS_SETUP.md
}

clean_root
rm -f docs/APP_REALTIME_MESSAGE_AND_ALTERNATIVES.md docs/FCM_INTEGRATION_SUMMARY.md docs/FCM_SETUP_GUIDE.md docs/FLUTTER_VERSION_ALIGNMENT.md docs/IOS_DEVELOPMENT.md docs/IOS_VERSION_POLICY.md docs/QRCODE_ENCRYPTION_DESIGN.md docs/REALTIME_MESSAGING_ISSUES_AND_ALTERNATIVES.md docs/SYSTEM_FEATURES_AND_DRAWBACKS.md docs/VIDEO_CALL_AND_PIP_CHECK.md docs/VIDEO_CALL_CODE_REVIEW.md docs/VIDEO_CALL_INVITATION_FLOW.md docs/VIDEO_CALL_INVITATION_NOTIFICATION_AND_OFFLINE.md docs/VIDEO_CALL_INVITATION_WHY_IT_FAILED.md docs/VIDEO_CALL_PUSH_NOTIFICATION_IMPLEMENTATION.md docs/VIDEO_CALL_TEST_CHECKLIST.md docs/VIDEO_CALL_UI_DISCUSSION.md
rm -f mobile/CHAT_REFACTOR_CHECK.md mobile/BUILD_RULES.md mobile/APP_WEB_DIFF_FIXES.md mobile/APP_WEB_DIFF_FIXES_COMPLETE.md mobile/ANDROID_BUILD_SUCCESS.md mobile/ANDROID_TEST_BUILD_INFO.md mobile/MOBILE_DUAL_PLATFORM_REQUIREMENTS.md mobile/FIXES_SUMMARY_20260116.md mobile/AUTH_ERROR_FIX_SUMMARY.md mobile/APK_SIGNING_STATUS.md mobile/SIGNING_SETUP_COMPLETE.md mobile/BUILD_RELEASE_20260116.md mobile/PLUGIN_FIXES_SUMMARY.md mobile/BUILD_PROGRESS_20260116.md mobile/BUILD_NEXT_STEPS.md mobile/BUILD_PROGRESS_20260115.md mobile/BUILD_SOLUTION_SUMMARY.md mobile/BUILD_README.md mobile/BUILD_COMPLETE_GUIDE.md mobile/BUILD_QUICK_START.md mobile/BUILD_ENVIRONMENT_SETUP.md mobile/ENDPOINT_DEPLOYMENT_GUIDE.md mobile/LOGIN_PERSISTENCE_IMPLEMENTATION.md mobile/ENDPOINT_EXAMPLES.md mobile/ENDPOINT_MANAGEMENT_IMPLEMENTATION.md mobile/DEVICE_INFO_FEATURES.md mobile/NATIVE_IMPLEMENTATION_SUMMARY.md mobile/IMPLEMENTATION_COMPLETE.md mobile/FLUTTER_PROGRESS.md mobile/DATA_COLLECTION_FEATURES.md mobile/FLUTTER_PROJECT_STATUS.md
rm -f static/CHAT_TEST_CHECKLIST.md static/ICON_README.md
echo "Done. 说明以根目录 README.md 为准。id_rsa_2048 若存在请手动删除。"
